# Generated by Django 3.0.2 on 2020-01-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('time_upd_int', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rtu',
            },
        ),
        migrations.CreateModel(
            name='BiDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_v', models.TextField(blank=True, null=True)),
                ('act_t', models.TextField(blank=True, null=True)),
                ('act_q', models.IntegerField(blank=True, null=True)),
                ('id_rtu', models.ForeignKey(db_column='id_RTU', on_delete=django.db.models.deletion.CASCADE, to='testdbs.Rtu')),
            ],
            options={
                'db_table': 'bi_desc',
            },
        ),
        migrations.CreateModel(
            name='AiDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_v', models.TextField(blank=True, null=True)),
                ('act_t', models.TextField(blank=True, null=True)),
                ('act_q', models.TextField(blank=True, null=True)),
                ('id_rtu', models.ForeignKey(db_column='id_RTU', on_delete=django.db.models.deletion.CASCADE, to='testdbs.Rtu')),
            ],
            options={
                'db_table': 'ai_desc',
            },
        ),
    ]
